/* eslint-disable */
export const Regexs = {
  ONLY_SPACE: /\s+/g,
  ONLY_COMMAS: /\,/g,
  PHONE_NUMBER: /^[+]?[(]?[0-9]{3}[)]?[-s.]?[0-9]{3}[-s.]?[0-9]{4,6}$/,
  UNFORMAT_PHONE_NUMBER: /[\(\)\s\-]/g,
  ALPHANUMBERIC_SPACE: /^[A-Za-z0-9\s]+$/,
  ONLY_NAME: /^[A-Za-z\s]+$/,
  INSURED_NAME: /^[A-Za-z0-9()Đđ\s]+$/,
  ADDRESS: /^[^`~!@#$%^&*()_+={}\[\]|\\:;“’<>.?๐฿]*$/,
  FREE_TEXT: /^[A-Za-z0-9\s\-\/\:\;\(\)\&\@\.\,\?\!\\_\\')]+$/,
  NAME: /^[^`~!@#$%^&*()_+={}\[\]|\\:;“’<>.?๐฿]*$/,
  INPUT_NAME: /^[A-Za-z'\s\-\']+$/,
  ANSWER_TEXT: /^[A-Za-z'\s\.\,\-\(\)\\\']+$/,
  ANSWER_TEXT_AND_NUMBER: /^[A-Za-z0-9]+$/,
  ALPHANUMBERIC_UPPERCASE: /^[A-Z0-9]+$/,
  ALPHANUMBERIC: /^[A-Za-z0-9]+$/,
  DECIMAL_NUMBER: /^[^.]*.?[^.]*$/,
  EMAIL: /^[a-zA-Z0-9]+([+.\-%]?[a-zA-Z0-9]+)*@[a-zA-Z0-9]+([\.-]?[a-zA-Z0-9]+)*(\.[a-zA-Z0-9]{2,4})+$/,
  EMAIL_LOCAL_PART: /^[a-zA-Z0-9._%+-]*$/,
  EMAIL_DOMAIN: /^^[a-zA-Z0-9.-]*$/,
  EMAIL_ROOT_DOMAIN: /^[a-zA-Z]{2,4}$/,
  DOMAIN: /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]$/,
  FIST_CHARACTER_NOT_SPACE: /^\S.*/,
  FIST_CHARACTER_NOT_SPECIAL: /^[^\-\s\'].*/,
  REFERENCE_INPUT: /^[a-zA-Z0-9$.,\s]+$/,
  PASSWORD: /^(?=.*\d)(?=.*[!"#$%&'()*+,-.\\\/:;<=>?@\[\]^_`{|}~])(?=.*[a-z])(?=.*[A-Z]).{12,}$/,
  CURRENCY_VALID: /^\$?(([1-9]\d{0,2}(,\d{3})*))(\.\d{1,2})?$/,
  START_DATE: /^(20)\d\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$/,
  ONLY_NUMBER: /^[0-9]*$/,
  UPERCASE_NUMBER: /^[A-Z0-9]*$/,
  ONLY_PASSPORT_NUMBER: /^[a-zA-Z0-9_]{8,9}$/,
  ONLY_IDENTITY_NUMBER: /^[a-zA-Z0-9_]{12}$/,
  ONLY_ID_NUMBER: /^[a-zA-Z0-9_]{9}$/,
  ONLY_ALPHABET: /^[a-zA-Z]+$/,
  DATE_FORMAT_DD_MM_YYYY: /^(0?[1-9]|[12][0-9]|3[01])\/(0?[1-9]|1[0-2])\/\d{4}$/
};
